spring:
  application:
    name: langrisser

  profiles:
    default: local

  datasource:
#    url: jdbc:h2:mem:~/langrisser
    url: jdbc:h2:tcp://localhost/~/langrisser
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: EMBEDDED

  h2:
    console:
      enabled: true
      path: /h2-console
